{
 "title": "Scenario 4 Dashboard (Ryan & Alexis) FINAL",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1d",
 "panels": [
  {
   "title": "Route Emitter Time to Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max_over_time(RouteEmitterSyncDuration{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"route_emitter\"}[15m]) / 1000000000",
     "legendFormat": "{{exported_job}}/{{ip}}"
    }
   ]
  },
  { "title": "Diego Locket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ActiveLocks{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"locket\"}[5m])",
     "legendFormat": "Active Locks"
    }
   ]
  },
  {
   "title": "Locks Held by BBS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(LockHeld{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[5m])",
     "legendFormat": "Lock Held by BBS"
    }
   ]
  },
  {
   "title": "Locks Held by Auctioneer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(LockHeld{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"auctioneer\"}[5m])",
     "legendFormat": "Lock Held"
    }
   ]
  },
  {
   "title": "Active Presences",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ActivePresences{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"locket\"}[15m])",
     "legendFormat": "Total count of active Presences"
    }
   ]
  },
  { "title": "Diego Cell", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Remaining Memory Available — Diego Cell Memory Chunks Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "CapacityRemainingMemory{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"rep\"} / 1000",
     "legendFormat": "{{exported_job}}/{{ip}}"
    }
   ]
  },
  {
   "title": "Remaining Disk Available — Diego Cell Disk Chunks Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "CapacityRemainingDisk{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"rep\"} / 1000",
     "legendFormat": "{{exported_job}}/{{ip}}"
    }
   ]
  },
  {
   "title": "Diego Cell Rep Time to Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(RepBulkSyncDuration{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"rep\"}[15m]) / 1000000000",
     "legendFormat": "{{exported_job}}/{{ip}}"
    }
   ]
  },
  {
   "title": "Garden Health Check Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(GardenHealthCheckFailed{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"rep\"}[5m])",
     "legendFormat": "Health Check Failure"
    }
   ]
  },
  { "title": "Diego BBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "BBS Time to Run LRP Convergence",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ConvergenceLRPDuration{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[15m]) / 1000000000",
     "legendFormat": "Time to run Convergence Pass"
    }
   ]
  },
  {
   "title": "BBS Time To Handle Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(RequestLatency{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[15m]) / 1000000000",
     "legendFormat": "AVG Request Latency"
    }
   ]
  },
  {
   "title": "Cloud Controller and Diego in Sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min_over_time(Domain_cf_apps{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[15m])",
     "legendFormat": "CC & Diego in Sync"
    }
   ]
  },
  {
   "title": "More App Instances Than Expected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(LRPsExtra{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[5m])",
     "legendFormat": "Extra LRPs"
    }
   ]
  },
  {
   "title": "Fewer App Instances Than Expected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(LRPsMissing{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[5m])",
     "legendFormat": "Missing LRPs"
    }
   ]
  },
  {
   "title": "Crashed App Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(CrashedActualLRPs{deployment=\"cf-7771bc8f714e4d087a30\",source_id=\"bbs\"}[5m])",
     "legendFormat": "Crashed LRPs"
    }
   ]
  },
  {
   "title": "Running App Instances, Rate of Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(LRPsRunning{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[1h]) - avg_over_time(LRPsRunning{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"bbs\"}[1h] offset 1h)",
     "legendFormat": "App Instance Change"
    }
   ]
  },
  {
   "title": "BBS Master Elected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "BBSMasterElected", "legendFormat": "BBS Master Election Occurred" }
   ]
  },
  { "title": "Diego Auctioneer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Auctioneer App Placement Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(AuctioneerLRPAuctionsFailed{deployment=\"cf-7771bc8f714e4d087a30\",source_id=\"auctioneer\"}[5m])",
     "legendFormat": "App Placement Failures"
    }
   ]
  },
  {
   "title": "Auctioneer Time to Fetch Diego Cell State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(AuctioneerFetchStatesDuration{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"auctioneer\"}[5m]) / 1000000000",
     "legendFormat": "AI Placement Failures"
    }
   ]
  },
  {
   "title": "Auctioneer App Instance Starts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(AuctioneerLRPAuctionsStarted{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"auctioneer\"}[5m])",
     "legendFormat": "LRPs Successfully Placed"
    }
   ]
  },
  {
   "title": "Auctioneer Task Placement Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(AuctioneerTaskAuctionsFailed{deployment=\"cf-7771bc8f714e4d087a30\", source_id=\"auctioneer\"} [5m])",
     "legendFormat": "Task Placement Failures"
    }
   ]
  }
 ]
}