{
 "title": "Metric Store",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Nozzle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nozzle Ingress Envelopes Total per min",
     "type": "graph",
     "description": "Number of envelopes sent to collocated Metric Store",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_nozzle_ingress_envelopes_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Nozzle Egress Points per min",
     "type": "graph",
     "description": "Number of points written to its collocated Metric Store",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_nozzle_egress_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Nozzle Egress Duration",
     "type": "graph",
     "description": "Total duration spent writing to points.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_nozzle_egress_duration_seconds_count{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Nozzle Dropped Envelopes per min",
     "type": "graph",
     "description": "Number of envelopes sent to collocated Metric Store",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_nozzle_dropped_envelopes_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Nozzle Dropped Points per min",
     "type": "graph",
     "description": "Number of points dropped in outbound channel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_nozzle_dropped_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Nozzle Egress Errors per min",
     "type": "graph",
     "description": "Number of errors writing to a remote node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_nozzle_egress_errors_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    }
   ]
  },
  {
   "title": "Metric Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric Store Disk Free",
     "type": "gauge",
     "description": "Percentage of free space on persistent disk",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metric_store_disk_free_ratio{deployment='metric-store-e0733717c583897f8286'}*100"
      }
     ]
    },
    {
     "title": "Metric Store Days of stored data",
     "type": "gauge",
     "description": "Days of data stored on disk",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "d" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "metric_store_storage_days{deployment='metric-store-e0733717c583897f8286'}"
      }
     ]
    },
    {
     "title": "Metric Store Ingress Points per min",
     "type": "graph",
     "description": "Number of points ingressed to colocated Metric Store",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_ingress_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Written Points per min",
     "type": "graph",
     "description": "Number of points succesfully written to storage engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_written_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Read Errors per min",
     "type": "graph",
     "description": "Number of errors encountered reading from the storage engine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_read_errors_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Writes Duration",
     "type": "graph",
     "description": "Time spent writing points to the storage engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_write_duration_seconds_count{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store measurement names query duration",
     "type": "graph",
     "description": "Time spent retrieving measurement names from the storage engine",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_measurement_names_query_duration_seconds_count{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      },
      {}
     ]
    },
    {
     "title": "Metric Store Tag values query duration",
     "type": "graph",
     "description": "Time spent retrieving tag values from the storage engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_tag_values_query_duration_seconds_count{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Measurements Count",
     "type": "graph",
     "description": "Number of unique measurements stored in the index",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "metric_store_measurements_count{deployment='metric-store-e0733717c583897f8286'}"
      }
     ]
    },
    {
     "title": "Metric Store Series Count",
     "type": "graph",
     "description": "Number of unique series stored in the index",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "metric_store_series_count{deployment='metric-store-e0733717c583897f8286'}"
      }
     ]
    },
    {
     "title": "Metric Store Expired Shards per min",
     "type": "graph",
     "description": "Number of shards removed due to time-based expiration",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_expired_shards_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Pruned Shards per min",
     "type": "graph",
     "description": "Number of shards removed due to disk space threshold",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_pruned_shards_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    }
   ]
  },
  {
   "title": "CF Auth Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth Proxy CAPI request duration",
     "type": "graph",
     "description": "Duration in seconds of external requests made to CAPI",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_auth_proxy_capi_request_duration_seconds_count{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Auth Proxy CAPI request duration",
     "type": "graph",
     "description": "Duration in seconds of external requests made to CAPI",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_auth_proxy_capi_request_duration_seconds_count{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    }
   ]
  },
  {
   "title": "Metric Store Remote",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Metric Store Distributed Points per min",
     "type": "graph",
     "description": "Number of points successfully distributed to a remote node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_distributed_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Collected Points per min",
     "type": "graph",
     "description": "Number of points collected by a metric-store instance from remote nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_collected_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Distributed Request duration",
     "type": "graph",
     "description": "Time spent distributing points to a remote node",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(metric_store_distributed_request_duration_seconds{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    },
    {
     "title": "Metric Store Points Dropped per min",
     "type": "graph",
     "description": "Number of points dropped while writing to a remote node",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(metric_store_dropped_points_total{deployment='metric-store-e0733717c583897f8286'}[60s:15s])"
      }
     ]
    }
   ]
  }
 ]
}