{
 "title": "Syslog_Agent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Syslog Agent Ingress Delta Diego Cell Scope Agent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(ingress{source_id='syslog_agent', exported_job='diego_cell', scope='agent'}[1m])",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Ingress Total Diego Cell Scope Agent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingress{source_id='syslog_agent', exported_job='diego_cell', scope='agent'}",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Ingress Delta Diego Cell Scope All Drains",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(ingress{source_id='syslog_agent', exported_job='diego_cell', scope='all_drains'}[1m])",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Ingress Total Diego Cell Scope All Drains",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ingress{source_id='syslog_agent', exported_job='diego_cell', scope='all_drains'}",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Ingress Drop Delta Diego Cell",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(dropped{source_id='syslog_agent', exported_job='diego_cell', direction='ingress'}[1m])",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Ingress Drop Total Diego Cell",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dropped{source_id='syslog_agent', exported_job='diego_cell', direction='ingress'}",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Egress Drop Delta Diego Cell",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(dropped{source_id='syslog_agent', exported_job='diego_cell', direction='egress'}[1m])",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Egress Drop Total Diego Cell",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dropped{source_id='syslog_agent', exported_job='diego_cell', direction='egress'}",
     "legendFormat": "{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Messages Per Drain Drop Delta Diego Cell",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(messages_dropped_per_drain{source_id='syslog_agent', exported_job='diego_cell'}[1m])",
     "legendFormat": "{{exported_job}}/{{index}}/{{drain_url}}"
    }
   ]
  },
  {
   "title": "Syslog Agent Messages Per Drain Drop Total Diego Cell",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "messages_dropped_per_drain{source_id='syslog_agent', exported_job='diego_cell', direction='egress'}",
     "legendFormat": "{{exported_job}}/{{index}}/{{drain_url}}"
    }
   ]
  }
 ]
}