{
 "title": "TAS-mysql",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Size",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_cluster_size{deployment=~\"cf.+\"}"
      }
     ]
    },
    {
     "title": "Cluster Status",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 6, "w": 22, "x": 2, "y": 1 },
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_cluster_status",
       "legendFormat": "Healthy"
      }
     ]
    },
    {
     "title": "MYSQL HA Cluster Node Ready",
     "type": "flant-statusmap-panel",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_ready{deployment=~\"cf.+\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  },
  {
   "title": "MYSQL CPU Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_mysql_performance_cpu_utilization_percent",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "MYSQL CPU Load AVG 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_1m{deployment=~\"cf.+\", exported_job=\"mysql\", origin=\"bosh-system-metrics-forwarder\"}"
    }
   ]
  },
  { "title": "Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "MYSQL Persistent Disk Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_mysql_system_persistent_disk_used_percent",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "MYSQL Memory Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{origin=\"bosh-system-metrics-forwarder\", deployment=~\"cf.+\", exported_job=\"mysql\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "MYSQL Ephemeral Disk Utilization Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "_mysql_system_ephemeral_disk_used_percent",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Connections Available",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "_mysql_variables_max_connections",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Max Connections Used All Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "_mysql_net_max_used_connections",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Current Open Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "_mysql_performance_threads_connected",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "MySQL Open Connection Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_performance_threads_connected",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Connection Attempts Delta",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(_mysql_net_connections[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "MySQL Threads Running",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_performance_threads_running",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total Queries",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "expr": "_mysql_performance_queries", "legendFormat": "{{index}}" }
     ]
    },
    {
     "title": "Slow Queries",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "_mysql_performance_slow_queries",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Flow Control Paused",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_flow_control_paused",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Receive Queue Lengh",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_local_recv_queue",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Queries Delta",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(_mysql_performance_queries[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Slow Queries Delta",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(_mysql_performance_slow_queries[1m])",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Flow Control Paused",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_flow_control_paused",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Local Receive Queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "_mysql_galera_wsrep_local_recv_queue",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}